{
  "version": "2.1.0",
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "fullName": "Docker Scout",
          "informationUri": "https://docker.com/products/docker-scout",
          "name": "docker scout",
          "rules": [
            {
              "id": "PYSEC-2022-252",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "PYSEC-2022-252"
              },
              "helpUri": "https://scout.docker.com/v/PYSEC-2022-252?s=pypa&n=deep-translator&t=pypi&vr=%3E%3D1.8.5",
              "help": {
                "text": "The deep-translator project on PyPI was taken over via user account compromise via a phishing attack and a new malicious release made which contained code which some environment variables and downloaded and ran malware at install time\n",
                "markdown": "> The deep-translator project on PyPI was taken over via user account compromise via a phishing attack and a new malicious release made which contained code which some environment variables and downloaded and ran malware at install time\n\n|                |                                 |\n|----------------|---------------------------------|\n| Package        | pkg:pypi/deep-translator@1.11.4 |\n| Affected range | >=1.8.5                         |\n| Fixed version  | not fixed                       |\n"
              },
              "properties": {
                "affected_version": ">=1.8.5",
                "cvssV3_severity": "UNSPECIFIED",
                "fixed_version": "not fixed",
                "purls": [
                  "pkg:pypi/deep-translator@1.11.4"
                ],
                "security-severity": "3.1",
                "tags": [
                  "UNSPECIFIED"
                ]
              }
            },
            {
              "id": "CVE-2024-34062",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-34062: Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-34062?s=github&n=tqdm&t=pypi&vr=%3E%3D4.4.0%2C%3C4.66.3",
              "help": {
                "text": "### Impact\nAny optional non-boolean CLI arguments (e.g. `--delim`, `--buf-size`, `--manpath`) are passed through python's `eval`, allowing arbitrary code execution. Example:\n\n```sh\npython -m tqdm --manpath=\"\\\" + str(exec(\\\"import os\\nos.system('echo hi && killall python3')\\\")) + \\\"\"\n```\n\n### Patches\nhttps://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316 released in `tqdm>=4.66.3`\n\n### Workarounds\nNone\n\n### References\n- https://github.com/tqdm/tqdm/releases/tag/v4.66.3\n",
                "markdown": "> ### Impact\nAny optional non-boolean CLI arguments (e.g. `--delim`, `--buf-size`, `--manpath`) are passed through python's `eval`, allowing arbitrary code execution. Example:\n\n```sh\npython -m tqdm --manpath=\"\\\" + str(exec(\\\"import os\\nos.system('echo hi && killall python3')\\\")) + \\\"\"\n```\n\n### Patches\nhttps://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316 released in `tqdm>=4.66.3`\n\n### Workarounds\nNone\n\n### References\n- https://github.com/tqdm/tqdm/releases/tag/v4.66.3\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/tqdm@4.66.2                         |\n| Affected range | >=4.4.0,<4.66.3                              |\n| Fixed version  | 4.66.3                                       |\n| CVSS Score     |                                          3.9 |\n| CVSS Vector    | CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N |\n"
              },
              "properties": {
                "affected_version": ">=4.4.0,<4.66.3",
                "cvssV3": 3.9,
                "cvssV3_severity": "LOW",
                "cvssV3_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N",
                "fixed_version": "4.66.3",
                "purls": [
                  "pkg:pypi/tqdm@4.66.2"
                ],
                "security-severity": "3.9",
                "tags": [
                  "LOW"
                ]
              }
            },
            {
              "id": "CVE-2024-0853",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-0853"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-0853?s=docker&n=curl&ns=alpine&t=apk&osn=alpine&osv=3.19&vr=%3C8.6.0-r0",
              "help": {
                "text": "\n",
                "markdown": "> \n\n|                |                                                             |\n|----------------|-------------------------------------------------------------|\n| Package        | pkg:apk/alpine/curl@8.5.0-r0?os_name=alpine&os_version=3.19 |\n| Affected range | <8.6.0-r0                                                   |\n| Fixed version  | not fixed                                                   |\n"
              },
              "properties": {
                "affected_version": "<8.6.0-r0",
                "cvssV3_severity": "MEDIUM",
                "fixed_version": "not fixed",
                "purls": [
                  "pkg:apk/alpine/curl@8.5.0-r0?os_name=alpine&os_version=3.19"
                ],
                "security-severity": "5.3",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2024-1681",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-1681: Improper Output Neutralization for Logs"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-1681?s=github&n=flask-cors&t=pypi&vr=%3C%3D4.0.0",
              "help": {
                "text": "corydolphin/flask-cors is vulnerable to log injection when the log level is set to debug. An attacker can inject fake log entries into the log file by sending a specially crafted GET request containing a CRLF sequence in the request path. This vulnerability allows attackers to corrupt log files, potentially covering tracks of other attacks, confusing log post-processing tools, and forging log entries. The issue is due to improper output neutralization for logs.\n",
                "markdown": "> corydolphin/flask-cors is vulnerable to log injection when the log level is set to debug. An attacker can inject fake log entries into the log file by sending a specially crafted GET request containing a CRLF sequence in the request path. This vulnerability allows attackers to corrupt log files, potentially covering tracks of other attacks, confusing log post-processing tools, and forging log entries. The issue is due to improper output neutralization for logs.\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/flask-cors@4.0.0                    |\n| Affected range | <=4.0.0                                      |\n| Fixed version  | 4.0.1                                        |\n| CVSS Score     |                                          5.3 |\n| CVSS Vector    | CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N |\n"
              },
              "properties": {
                "affected_version": "<=4.0.0",
                "cvssV3": 5.3,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
                "fixed_version": "4.0.1",
                "purls": [
                  "pkg:pypi/flask-cors@4.0.0"
                ],
                "security-severity": "5.3",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2024-34064",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-34064: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-34064?s=github&n=jinja2&t=pypi&vr=%3C3.1.4",
              "help": {
                "text": "The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.\n",
                "markdown": "> The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/jinja2@3.1.3                        |\n| Affected range | <3.1.4                                       |\n| Fixed version  | 3.1.4                                        |\n| CVSS Score     |                                          5.4 |\n| CVSS Vector    | CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N |\n"
              },
              "properties": {
                "affected_version": "<3.1.4",
                "cvssV3": 5.4,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "fixed_version": "3.1.4",
                "purls": [
                  "pkg:pypi/jinja2@3.1.3"
                ],
                "security-severity": "5.4",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2023-42364",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2023-42364"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2023-42364?s=alpine&n=busybox&ns=alpine&t=apk&osn=alpine&osv=3.19&vr=%3C1.36.1-r19",
              "help": {
                "text": "\n",
                "markdown": "> \n\n|                |                                                                  |\n|----------------|------------------------------------------------------------------|\n| Package        | pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19 |\n| Affected range | <1.36.1-r19                                                      |\n| Fixed version  | 1.36.1-r19                                                       |\n"
              },
              "properties": {
                "affected_version": "<1.36.1-r19",
                "cvssV3_severity": "MEDIUM",
                "fixed_version": "1.36.1-r19",
                "purls": [
                  "pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19"
                ],
                "security-severity": "5.5",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2023-42365",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2023-42365"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2023-42365?s=alpine&n=busybox&ns=alpine&t=apk&osn=alpine&osv=3.19&vr=%3C1.36.1-r19",
              "help": {
                "text": "\n",
                "markdown": "> \n\n|                |                                                                  |\n|----------------|------------------------------------------------------------------|\n| Package        | pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19 |\n| Affected range | <1.36.1-r19                                                      |\n| Fixed version  | 1.36.1-r19                                                       |\n"
              },
              "properties": {
                "affected_version": "<1.36.1-r19",
                "cvssV3_severity": "MEDIUM",
                "fixed_version": "1.36.1-r19",
                "purls": [
                  "pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19"
                ],
                "security-severity": "5.5",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2024-35195",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-35195: Always-Incorrect Control Flow Implementation"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-35195?s=github&n=requests&t=pypi&vr=%3C2.32.0",
              "help": {
                "text": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655\n",
                "markdown": "> When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/requests@2.31.0                     |\n| Affected range | <2.32.0                                      |\n| Fixed version  | 2.32.0                                       |\n| CVSS Score     |                                          5.6 |\n| CVSS Vector    | CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N |\n"
              },
              "properties": {
                "affected_version": "<2.32.0",
                "cvssV3": 5.6,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "fixed_version": "2.32.0",
                "purls": [
                  "pkg:pypi/requests@2.31.0"
                ],
                "security-severity": "5.6",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2024-3651",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-3651: Uncontrolled Resource Consumption"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-3651?s=github&n=idna&t=pypi&vr=%3C3.7",
              "help": {
                "text": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb\n",
                "markdown": "> ### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/idna@3.6                            |\n| Affected range | <3.7                                         |\n| Fixed version  |                                          3.7 |\n| CVSS Score     |                                          6.2 |\n| CVSS Vector    | CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H |\n"
              },
              "properties": {
                "affected_version": "<3.7",
                "cvssV3": 6.2,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "fixed_version": "3.7",
                "purls": [
                  "pkg:pypi/idna@3.6"
                ],
                "security-severity": "6.2",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "GHSA-c827-hfw6-qwvm",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "GHSA-c827-hfw6-qwvm"
              },
              "helpUri": "https://scout.docker.com/v/GHSA-c827-hfw6-qwvm?s=github&n=rustix&t=cargo&vr=%3E%3D0.37.0%2C%3C0.37.25",
              "help": {
                "text": "### Summary\n\nWhen using `rustix::fs::Dir` using the `linux_raw` backend, it's possible for the iterator to \"get stuck\" when an IO error is encountered. Combined with a memory over-allocation issue in `rustix::fs::Dir::read_more`, this can cause quick and unbounded memory explosion (gigabytes in a few seconds if used on a hot path) and eventually lead to an OOM crash of the application.\n\n### Details\n\n#### Discovery\n\nThe symptoms were initially discovered in https://github.com/imsnif/bandwhich/issues/284. That post has lots of details of our investigation. See [this post](https://github.com/imsnif/bandwhich/issues/284#issuecomment-1754321993) and the [Discord thread](https://discord.com/channels/273534239310479360/1161137828395237556) for details.\n\n#### Diagnosis\n\nThis issue is caused by the combination of two independent bugs:\n\n1. Stuck iterator\n- The `rustix::fs::Dir` iterator can fail to halt after encountering an IO error, causing the caller to be stuck in an infinite loop.\n2. Memory over-allocation\n- `Dir::read_more` incorrectly grows the read buffer unconditionally each time it is called, regardless of necessity.\n\nSince `<Dir as Iterator>::next` calls `Dir::read`, which in turn calls `Dir::read_more`, this means an IO error encountered during reading a directory can lead to rapid and unbounded growth of memory use.\n\n### PoC\n\n```rust\nfn main() -> Result<(), Box<dyn std::error::Error>> {\n    // create a directory, get a FD to it, then unlink the directory but keep the FD\n    std::fs::create_dir(\"tmp_dir\")?;\n    let dir_fd = rustix::fs::openat(\n        rustix::fs::CWD,\n        rustix::cstr!(\"tmp_dir\"),\n        rustix::fs::OFlags::RDONLY | rustix::fs::OFlags::CLOEXEC,\n        rustix::fs::Mode::empty(),\n    )?;\n    std::fs::remove_dir(\"tmp_dir\")?;\n\n    // iterator gets stuck in infinite loop and memory explodes\n    rustix::fs::Dir::read_from(dir_fd)?\n        // the iterator keeps returning `Some(Err(_))`, but never halts by returning `None`\n        // therefore if the implementation ignores the error (or otherwise continues\n        // after seeing the error instead of breaking), the loop will not halt\n        .filter_map(|dirent_maybe_error| dirent_maybe_error.ok())\n        .for_each(|dirent| {\n            // your happy path\n            println!(\"{dirent:?}\");\n        });\n\n    Ok(())\n}\n```\n\n### Impact\n\nIf a program tries to access a directory with its file descriptor after the file has been unlinked (or any other action that leaves the `Dir` iterator in the stuck state), and the implementation does not break after seeing an error, it can cause a memory explosion.\n\nAs an example, Linux's various virtual file systems (e.g. `/proc`, `/sys`) can contain directories that spontaneously pop in and out of existence. Attempting to iterate over them using `rustix::fs::Dir` directly or indirectly (e.g. with the `procfs` crate) can trigger this fault condition if the implementation decides to continue on errors.\n\nAn attacker knowledgeable about the implementation details of a vulnerable target can therefore try to trigger this fault condition via any one or a combination of several available APIs. If successful, the application host will quickly run out of memory, after which the application will likely be terminated by an OOM killer, leading to denial of service.\n",
                "markdown": "> ### Summary\n\nWhen using `rustix::fs::Dir` using the `linux_raw` backend, it's possible for the iterator to \"get stuck\" when an IO error is encountered. Combined with a memory over-allocation issue in `rustix::fs::Dir::read_more`, this can cause quick and unbounded memory explosion (gigabytes in a few seconds if used on a hot path) and eventually lead to an OOM crash of the application.\n\n### Details\n\n#### Discovery\n\nThe symptoms were initially discovered in https://github.com/imsnif/bandwhich/issues/284. That post has lots of details of our investigation. See [this post](https://github.com/imsnif/bandwhich/issues/284#issuecomment-1754321993) and the [Discord thread](https://discord.com/channels/273534239310479360/1161137828395237556) for details.\n\n#### Diagnosis\n\nThis issue is caused by the combination of two independent bugs:\n\n1. Stuck iterator\n- The `rustix::fs::Dir` iterator can fail to halt after encountering an IO error, causing the caller to be stuck in an infinite loop.\n2. Memory over-allocation\n- `Dir::read_more` incorrectly grows the read buffer unconditionally each time it is called, regardless of necessity.\n\nSince `<Dir as Iterator>::next` calls `Dir::read`, which in turn calls `Dir::read_more`, this means an IO error encountered during reading a directory can lead to rapid and unbounded growth of memory use.\n\n### PoC\n\n```rust\nfn main() -> Result<(), Box<dyn std::error::Error>> {\n    // create a directory, get a FD to it, then unlink the directory but keep the FD\n    std::fs::create_dir(\"tmp_dir\")?;\n    let dir_fd = rustix::fs::openat(\n        rustix::fs::CWD,\n        rustix::cstr!(\"tmp_dir\"),\n        rustix::fs::OFlags::RDONLY | rustix::fs::OFlags::CLOEXEC,\n        rustix::fs::Mode::empty(),\n    )?;\n    std::fs::remove_dir(\"tmp_dir\")?;\n\n    // iterator gets stuck in infinite loop and memory explodes\n    rustix::fs::Dir::read_from(dir_fd)?\n        // the iterator keeps returning `Some(Err(_))`, but never halts by returning `None`\n        // therefore if the implementation ignores the error (or otherwise continues\n        // after seeing the error instead of breaking), the loop will not halt\n        .filter_map(|dirent_maybe_error| dirent_maybe_error.ok())\n        .for_each(|dirent| {\n            // your happy path\n            println!(\"{dirent:?}\");\n        });\n\n    Ok(())\n}\n```\n\n### Impact\n\nIf a program tries to access a directory with its file descriptor after the file has been unlinked (or any other action that leaves the `Dir` iterator in the stuck state), and the implementation does not break after seeing an error, it can cause a memory explosion.\n\nAs an example, Linux's various virtual file systems (e.g. `/proc`, `/sys`) can contain directories that spontaneously pop in and out of existence. Attempting to iterate over them using `rustix::fs::Dir` directly or indirectly (e.g. with the `procfs` crate) can trigger this fault condition if the implementation decides to continue on errors.\n\nAn attacker knowledgeable about the implementation details of a vulnerable target can therefore try to trigger this fault condition via any one or a combination of several available APIs. If successful, the application host will quickly run out of memory, after which the application will likely be terminated by an OOM killer, leading to denial of service.\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:cargo/rustix@0.37.19                     |\n| Affected range | >=0.37.0,<0.37.25                            |\n| Fixed version  | 0.37.25                                      |\n| CVSS Score     |                                          6.5 |\n| CVSS Vector    | CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H |\n"
              },
              "properties": {
                "affected_version": ">=0.37.0,<0.37.25",
                "cvssV3": 6.5,
                "cvssV3_severity": "MEDIUM",
                "cvssV3_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "fixed_version": "0.37.25",
                "purls": [
                  "pkg:cargo/rustix@0.37.19"
                ],
                "security-severity": "6.5",
                "tags": [
                  "MEDIUM"
                ]
              }
            },
            {
              "id": "CVE-2024-34069",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2024-34069: Cross-Site Request Forgery (CSRF)"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2024-34069?s=github&n=werkzeug&t=pypi&vr=%3C3.0.3",
              "help": {
                "text": "The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.\n",
                "markdown": "> The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/werkzeug@3.0.1                      |\n| Affected range | <3.0.3                                       |\n| Fixed version  | 3.0.3                                        |\n| CVSS Score     |                                          7.5 |\n| CVSS Vector    | CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H |\n"
              },
              "properties": {
                "affected_version": "<3.0.3",
                "cvssV3": 7.5,
                "cvssV3_severity": "HIGH",
                "cvssV3_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "fixed_version": "3.0.3",
                "purls": [
                  "pkg:pypi/werkzeug@3.0.1"
                ],
                "security-severity": "7.5",
                "tags": [
                  "HIGH"
                ]
              }
            },
            {
              "id": "CVE-2018-20225",
              "name": "OsPackageVulnerability",
              "shortDescription": {
                "text": "CVE-2018-20225: OWASP Top Ten 2017 Category A9 - Using Components with Known Vulnerabilities"
              },
              "helpUri": "https://scout.docker.com/v/CVE-2018-20225?s=gitlab&n=pip&t=pypi&vr=%3E%3D0",
              "help": {
                "text": "An issue was discovered in pip (all versions) because it installs the version with the highest version number, even if the user had intended to obtain a private package from a private index. This only affects use of the `--extra-index-url` option, and exploitation requires that the package does not already exist in the public index (and thus the attacker can put the package there with an arbitrary version number).\n",
                "markdown": "> An issue was discovered in pip (all versions) because it installs the version with the highest version number, even if the user had intended to obtain a private package from a private index. This only affects use of the `--extra-index-url` option, and exploitation requires that the package does not already exist in the public index (and thus the attacker can put the package there with an arbitrary version number).\n\n|                |                                              |\n|----------------|----------------------------------------------|\n| Package        | pkg:pypi/pip@24.0                            |\n| Affected range | >=0                                          |\n| Fixed version  | not fixed                                    |\n| CVSS Score     |                                          7.8 |\n| CVSS Vector    | CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H |\n"
              },
              "properties": {
                "affected_version": ">=0",
                "cvssV3": 7.8,
                "cvssV3_severity": "HIGH",
                "cvssV3_vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "fixed_version": "not fixed",
                "purls": [
                  "pkg:pypi/pip@24.0"
                ],
                "security-severity": "7.8",
                "tags": [
                  "HIGH"
                ]
              }
            }
          ],
          "version": "1.9.3"
        }
      },
      "results": [
        {
          "ruleId": "PYSEC-2022-252",
          "ruleIndex": 0,
          "kind": "fail",
          "level": "none",
          "message": {
            "text": "  Vulnerability  : PYSEC-2022-252                   \n  Severity       : UNSPECIFIED                      \n  Package        : pkg:pypi/deep-translator@1.11.4  \n  Affected range : >=1.8.5                          \n  Fixed version  : not fixed                        \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/deep_translator-1.11.4.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/deep_translator-1.11.4.dist-info/RECORD"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-34062",
          "ruleIndex": 1,
          "kind": "fail",
          "level": "note",
          "message": {
            "text": "  Vulnerability   : CVE-2024-34062                                \n  Severity        : LOW                                           \n  Package         : pkg:pypi/tqdm@4.66.2                          \n  Affected range  : >=4.4.0,<4.66.3                               \n  Fixed version   : 4.66.3                                        \n  CVSS Score      : 3.9                                           \n  CVSS Vector     : CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N  \n  EPSS Score      : 0.000450                                      \n  EPSS Percentile : 0.154970                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/tqdm-4.66.2.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/tqdm-4.66.2.dist-info/RECORD"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/tqdm-4.66.2.dist-info/top_level.txt"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-0853",
          "ruleIndex": 2,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2024-0853                                                \n  Severity        : MEDIUM                                                       \n  Package         : pkg:apk/alpine/curl@8.5.0-r0?os_name=alpine&os_version=3.19  \n  Affected range  : <8.6.0-r0                                                    \n  Fixed version   : not fixed                                                    \n  EPSS Score      : 0.000580                                                     \n  EPSS Percentile : 0.241940                                                     \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lib/apk/db/installed"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/bin/curl"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/libcurl.so.4.8.0"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-1681",
          "ruleIndex": 3,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2024-1681                                 \n  Severity        : MEDIUM                                        \n  Package         : pkg:pypi/flask-cors@4.0.0                     \n  Affected range  : <=4.0.0                                       \n  Fixed version   : 4.0.1                                         \n  CVSS Score      : 5.3                                           \n  CVSS Vector     : CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N  \n  EPSS Score      : 0.000430                                      \n  EPSS Percentile : 0.089710                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/Flask_Cors-4.0.0.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/Flask_Cors-4.0.0.dist-info/RECORD"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/Flask_Cors-4.0.0.dist-info/top_level.txt"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-34064",
          "ruleIndex": 4,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2024-34064                                \n  Severity        : MEDIUM                                        \n  Package         : pkg:pypi/jinja2@3.1.3                         \n  Affected range  : <3.1.4                                        \n  Fixed version   : 3.1.4                                         \n  CVSS Score      : 5.4                                           \n  CVSS Vector     : CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N  \n  EPSS Score      : 0.000440                                      \n  EPSS Percentile : 0.102860                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/Jinja2-3.1.3.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/Jinja2-3.1.3.dist-info/RECORD"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/Jinja2-3.1.3.dist-info/top_level.txt"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2023-42364",
          "ruleIndex": 5,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2023-42364                                                    \n  Severity        : MEDIUM                                                            \n  Package         : pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19  \n  Affected range  : <1.36.1-r19                                                       \n  Fixed version   : 1.36.1-r19                                                        \n  EPSS Score      : 0.000440                                                          \n  EPSS Percentile : 0.127180                                                          \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lib/apk/db/installed"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/share/udhcpc/default.script"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/bin/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/busybox-paths.d/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/logrotate.d/acpid"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/network/if-up.d/dad"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/securetty"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpc/udhcpc.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpd.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/bin/ssl_client"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2023-42365",
          "ruleIndex": 6,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2023-42365                                                    \n  Severity        : MEDIUM                                                            \n  Package         : pkg:apk/alpine/busybox@1.36.1-r18?os_name=alpine&os_version=3.19  \n  Affected range  : <1.36.1-r19                                                       \n  Fixed version   : 1.36.1-r19                                                        \n  EPSS Score      : 0.000440                                                          \n  EPSS Percentile : 0.127180                                                          \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lib/apk/db/installed"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/share/udhcpc/default.script"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/bin/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/busybox-paths.d/busybox"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/logrotate.d/acpid"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/network/if-up.d/dad"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/securetty"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpc/udhcpc.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/etc/udhcpd.conf"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/bin/ssl_client"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-35195",
          "ruleIndex": 7,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability   : CVE-2024-35195                                \n  Severity        : MEDIUM                                        \n  Package         : pkg:pypi/requests@2.31.0                      \n  Affected range  : <2.32.0                                       \n  Fixed version   : 2.32.0                                        \n  CVSS Score      : 5.6                                           \n  CVSS Vector     : CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N  \n  EPSS Score      : 0.000450                                      \n  EPSS Percentile : 0.154970                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/requests-2.31.0.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/requests-2.31.0.dist-info/RECORD"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/requests-2.31.0.dist-info/top_level.txt"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-3651",
          "ruleIndex": 8,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability  : CVE-2024-3651                                 \n  Severity       : MEDIUM                                        \n  Package        : pkg:pypi/idna@3.6                             \n  Affected range : <3.7                                          \n  Fixed version  : 3.7                                           \n  CVSS Score     : 6.2                                           \n  CVSS Vector    : CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H  \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/idna-3.6.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/idna-3.6.dist-info/RECORD"
                }
              }
            }
          ]
        },
        {
          "ruleId": "GHSA-c827-hfw6-qwvm",
          "ruleIndex": 9,
          "kind": "fail",
          "level": "warning",
          "message": {
            "text": "  Vulnerability  : GHSA-c827-hfw6-qwvm                           \n  Severity       : MEDIUM                                        \n  Package        : pkg:cargo/rustix@0.37.19                      \n  Affected range : >=0.37.0,<0.37.25                             \n  Fixed version  : 0.37.25                                       \n  CVSS Score     : 6.5                                           \n  CVSS Vector    : CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H  \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/usr/lib/librav1e.so.0.6.6"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2024-34069",
          "ruleIndex": 10,
          "kind": "fail",
          "level": "error",
          "message": {
            "text": "  Vulnerability   : CVE-2024-34069                                \n  Severity        : HIGH                                          \n  Package         : pkg:pypi/werkzeug@3.0.1                       \n  Affected range  : <3.0.3                                        \n  Fixed version   : 3.0.3                                         \n  CVSS Score      : 7.5                                           \n  CVSS Vector     : CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H  \n  EPSS Score      : 0.000450                                      \n  EPSS Percentile : 0.154970                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/werkzeug-3.0.1.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/app/bazarr/bin/libs/werkzeug-3.0.1.dist-info/RECORD"
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2018-20225",
          "ruleIndex": 11,
          "kind": "fail",
          "level": "error",
          "message": {
            "text": "  Vulnerability   : CVE-2018-20225                                \n  Severity        : HIGH                                          \n  Package         : pkg:pypi/pip@24.0                             \n  Affected range  : >=0                                           \n  Fixed version   : not fixed                                     \n  CVSS Score      : 7.8                                           \n  CVSS Vector     : CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H  \n  EPSS Score      : 0.001120                                      \n  EPSS Percentile : 0.447580                                      \n"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lsiopy/lib/python3.11/site-packages/pip-24.0.dist-info/METADATA"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lsiopy/lib/python3.11/site-packages/pip-24.0.dist-info/RECORD"
                }
              }
            },
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "/lsiopy/lib/python3.11/site-packages/pip-24.0.dist-info/top_level.txt"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
