redmine:alpine3.20 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_redmine:alpine3.20_2024-06-11_18:22:16.json redmine:alpine3.20] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
redmine:alpine ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_redmine:alpine_2024-06-11_18:22:50.json redmine:alpine] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
redmine:5.1.2-alpine3.20 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_redmine:5.1.2-alpine3.20_2024-06-11_18:23:16.json redmine:5.1.2-alpine3.20] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
redmine:5.1.2-alpine ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_redmine:5.1.2-alpine_2024-06-11_18:23:43.json redmine:5.1.2-alpine] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
redmine:5.1-alpine3.20 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_redmine:5.1-alpine3.20_2024-06-11_18:24:08.json redmine:5.1-alpine3.20] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nats:scratch ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_nats:scratch_2024-06-11_18:24:37.json nats:scratch] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
nats:linux ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_nats:linux_2024-06-11_18:24:44.json nats:linux] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
nats:alpine3.19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_nats:alpine3.19_2024-06-11_18:24:51.json nats:alpine3.19] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nats:alpine ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_nats:alpine_2024-06-11_18:24:59.json nats:alpine] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
nats:2.9.25-scratch ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_nats:2.9.25-scratch_2024-06-11_18:25:08.json nats:2.9.25-scratch] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
rocket.chat:6.6.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_rocket.chat:6.6.6_2024-06-11_18:25:16.json rocket.chat:6.6.6] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
rocket.chat:6.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_rocket.chat:6.6_2024-06-11_18:27:51.json rocket.chat:6.6] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
rocket.chat:6.5.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_rocket.chat:6.5.5_2024-06-11_18:29:34.json rocket.chat:6.5.5] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
rocket.chat:6.5 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_rocket.chat:6.5_2024-06-11_18:31:31.json rocket.chat:6.5] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
rocket.chat:6.7.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_rocket.chat:6.7.0_2024-06-11_18:33:16.json rocket.chat:6.7.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
docker:windowsservercore-ltsc2022 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_docker:windowsservercore-ltsc2022_2024-06-11_18:35:22.json docker:windowsservercore-ltsc2022] execution failed: exit status 1
Output: [31m2 errors occurred:
	* failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)
	* failed to catalog: an error occurred attempting to resolve 'windowsservercore-ltsc2022': docker: pull failed: Error response from daemon: pull access denied for windowsservercore-ltsc2022, repository does not exist or may require 'docker login': denied: requested access to the resource is denied[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_docker:windowsservercore-ltsc2022_2024-06-11_18:35:22.json docker:windowsservercore-ltsc2022] execution failed: exit status 1
Output: 2024-06-11T18:35:23Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:35:24Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "docker:windowsservercore-ltsc2022" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (docker:windowsservercore-ltsc2022): Error response from daemon: No such image: docker:windowsservercore-ltsc2022
	* containerd error: image not found in containerd store: docker:windowsservercore-ltsc2022
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: no child with platform linux/amd64 in index docker:windowsservercore-ltsc2022


 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test docker:windowsservercore-ltsc2022 --sarif-file-output=/mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Snyk_scan_docker:windowsservercore-ltsc2022_2024-06-11_18:35:22.json] execution failed: exit status 2
Output: The image does not exist for the current platform
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
docker:windowsservercore-1809 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_docker:windowsservercore-1809_2024-06-11_18:39:02.json docker:windowsservercore-1809] execution failed: exit status 1
Output: [31m2 errors occurred:
	* failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)
	* failed to catalog: an error occurred attempting to resolve 'windowsservercore-1809': docker: pull failed: Error response from daemon: pull access denied for windowsservercore-1809, repository does not exist or may require 'docker login': denied: requested access to the resource is denied[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_docker:windowsservercore-1809_2024-06-11_18:39:02.json docker:windowsservercore-1809] execution failed: exit status 1
Output: 2024-06-11T18:39:03Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:39:04Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "docker:windowsservercore-1809" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (docker:windowsservercore-1809): Error response from daemon: No such image: docker:windowsservercore-1809
	* containerd error: image not found in containerd store: docker:windowsservercore-1809
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: no child with platform linux/amd64 in index docker:windowsservercore-1809


 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test docker:windowsservercore-1809 --sarif-file-output=/mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Snyk_scan_docker:windowsservercore-1809_2024-06-11_18:39:02.json] execution failed: exit status 2
Output: The image does not exist for the current platform
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil>
docker:windowsservercore ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_docker:windowsservercore_2024-06-11_18:42:45.json docker:windowsservercore] execution failed: exit status 1
Output: [31m2 errors occurred:
	* failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)
	* failed to catalog: an error occurred attempting to resolve 'windowsservercore': docker: pull failed: Error response from daemon: pull access denied for windowsservercore, repository does not exist or may require 'docker login': denied: requested access to the resource is denied[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_docker:windowsservercore_2024-06-11_18:42:45.json docker:windowsservercore] execution failed: exit status 1
Output: 2024-06-11T18:42:45Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:42:46Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "docker:windowsservercore" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (docker:windowsservercore): Error response from daemon: No such image: docker:windowsservercore
	* containerd error: image not found in containerd store: docker:windowsservercore
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: no child with platform linux/amd64 in index docker:windowsservercore


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_docker:windowsservercore_2024-06-11_18:42:45.json docker:windowsservercore] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image docker:windowsservercore: failed to pull image docker:windowsservercore: no child with platform linux/amd64 in index docker:windowsservercore, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> Command [/usr/local/bin/snyk container test docker:windowsservercore --sarif-file-output=/mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Snyk_scan_docker:windowsservercore_2024-06-11_18:42:45.json] execution failed: exit status 2
Output: The image does not exist for the current platform

docker:dind-rootless ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_docker:dind-rootless_2024-06-11_18:42:53.json docker:dind-rootless] execution failed: exit status 1
Output: [31m2 errors occurred:
	* failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)
	* failed to catalog: an error occurred attempting to resolve 'dind-rootless': docker: pull failed: Error response from daemon: pull access denied for dind-rootless, repository does not exist or may require 'docker login': denied: requested access to the resource is denied[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
docker:dind ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_docker:dind_2024-06-11_18:43:19.json docker:dind] execution failed: exit status 1
Output: [31m2 errors occurred:
	* failed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)
	* failed to catalog: an error occurred attempting to resolve 'dind': docker: pull failed: Error response from daemon: pull access denied for dind, repository does not exist or may require 'docker login': denied: requested access to the resource is denied[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
tomee:9.1.3-jre17-Temurin-webprofile ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_tomee:9.1.3-jre17-Temurin-webprofile_2024-06-11_18:43:45.json tomee:9.1.3-jre17-Temurin-webprofile] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
tomee:9.1.3-jre17-Temurin-ubuntu-webprofile ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_tomee:9.1.3-jre17-Temurin-ubuntu-webprofile_2024-06-11_18:44:08.json tomee:9.1.3-jre17-Temurin-ubuntu-webprofile] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
tomee:9.1.3-jre17-Semeru-webprofile ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_tomee:9.1.3-jre17-Semeru-webprofile_2024-06-11_18:44:30.json tomee:9.1.3-jre17-Semeru-webprofile] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
tomee:9.1.3-jre17-Semeru-ubuntu-webprofile ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_tomee:9.1.3-jre17-Semeru-ubuntu-webprofile_2024-06-11_18:44:55.json tomee:9.1.3-jre17-Semeru-ubuntu-webprofile] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
tomee:9.1.3-jre17-Semeru-ubuntu-plus ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_tomee:9.1.3-jre17-Semeru-ubuntu-plus_2024-06-11_18:45:20.json tomee:9.1.3-jre17-Semeru-ubuntu-plus] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
bonita:9.0.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_bonita:9.0.0_2024-06-11_18:45:44.json bonita:9.0.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
bonita:9.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_bonita:9.0_2024-06-11_18:46:08.json bonita:9.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
bonita:8.0.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_bonita:8.0.0_2024-06-11_18:46:30.json bonita:8.0.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
bonita:8.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_bonita:8.0_2024-06-11_18:46:51.json bonita:8.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
bonita:2023.2-u0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_bonita:2023.2-u0_2024-06-11_18:47:12.json bonita:2023.2-u0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
solr:slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_solr:slim_2024-06-11_18:47:34.json solr:slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
solr:9.6.1-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_solr:9.6.1-slim_2024-06-11_18:47:57.json solr:9.6.1-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
solr:9.6.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_solr:9.6.1_2024-06-11_18:48:24.json solr:9.6.1] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
solr:9.6-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_solr:9.6-slim_2024-06-11_18:49:00.json solr:9.6-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
solr:9.6 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_solr:9.6_2024-06-11_18:49:22.json solr:9.6] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
neo4j:ubi9 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_neo4j:ubi9_2024-06-11_18:49:56.json neo4j:ubi9] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
neo4j:ubi8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_neo4j:ubi8_2024-06-11_18:50:33.json neo4j:ubi8] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
neo4j:enterprise-ubi9 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_neo4j:enterprise-ubi9_2024-06-11_18:51:20.json neo4j:enterprise-ubi9] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

neo4j:enterprise-ubi8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_neo4j:enterprise-ubi8_2024-06-11_18:52:06.json neo4j:enterprise-ubi8] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
neo4j:community-ubi9 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_neo4j:community-ubi9_2024-06-11_18:52:57.json neo4j:community-ubi9] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
erlang:20.3.8.26-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_erlang:20.3.8.26-slim_2024-06-11_18:53:30.json erlang:20.3.8.26-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
erlang:20.3.8-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_erlang:20.3.8-slim_2024-06-11_18:53:50.json erlang:20.3.8-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
erlang:20.3-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_erlang:20.3-slim_2024-06-11_18:54:10.json erlang:20.3-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
erlang:20-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_erlang:20-slim_2024-06-11_18:54:29.json erlang:20-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
erlang:22.3.4.27-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_erlang:22.3.4.27-slim_2024-06-11_18:54:48.json erlang:22.3.4.27-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
photon:5.0-20240602 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_photon:5.0-20240602_2024-06-11_18:55:10.json photon:5.0-20240602] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
photon:5.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_photon:5.0_2024-06-11_18:55:17.json photon:5.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
photon:4.0-20240602 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_photon:4.0-20240602_2024-06-11_18:55:25.json photon:4.0-20240602] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
photon:4.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_photon:4.0_2024-06-11_18:55:32.json photon:4.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
photon:3.0-20240602 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_photon:3.0-20240602_2024-06-11_18:55:39.json photon:3.0-20240602] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
couchdb:3.3.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_couchdb:3.3.3_2024-06-11_18:55:46.json couchdb:3.3.3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
couchdb:3.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_couchdb:3.3_2024-06-11_18:56:03.json couchdb:3.3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
couchdb:3.1.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_couchdb:3.1.2_2024-06-11_18:56:19.json couchdb:3.1.2] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image couchdb:3.1.2: failed to pull image couchdb:3.1.2: GET https://index.docker.io/v2/library/couchdb/manifests/3.1.2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_couchdb:3.1.2_2024-06-11_18:56:19.json couchdb:3.1.2] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
couchdb:3.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_couchdb:3.1_2024-06-11_18:56:34.json couchdb:3.1] execution failed: exit status 1
Output: 2024-06-11T18:56:35Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:56:36Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "couchdb:3.1" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (couchdb:3.1): Error response from daemon: No such image: couchdb:3.1
	* containerd error: image not found in containerd store: couchdb:3.1
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/couchdb/manifests/3.1: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_couchdb:3.1_2024-06-11_18:56:34.json couchdb:3.1] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image couchdb:3.1: failed to pull image couchdb:3.1: GET https://index.docker.io/v2/library/couchdb/manifests/3.1: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_couchdb:3.1_2024-06-11_18:56:34.json couchdb:3.1] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
couchdb:3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_couchdb:3_2024-06-11_18:56:56.json couchdb:3] execution failed: exit status 1
Output: 2024-06-11T18:56:57Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:56:58Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "couchdb:3" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (couchdb:3): Error response from daemon: No such image: couchdb:3
	* containerd error: image not found in containerd store: couchdb:3
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/couchdb/manifests/3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_couchdb:3_2024-06-11_18:56:56.json couchdb:3] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image couchdb:3: failed to pull image couchdb:3: GET https://index.docker.io/v2/library/couchdb/manifests/3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_couchdb:3_2024-06-11_18:56:56.json couchdb:3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
notary:signer-0.7.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_notary:signer-0.7.0_2024-06-11_18:57:14.json notary:signer-0.7.0] execution failed: exit status 1
Output: 2024-06-11T18:57:15Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:57:15Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "notary:signer-0.7.0" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (notary:signer-0.7.0): Error response from daemon: No such image: notary:signer-0.7.0
	* containerd error: image not found in containerd store: notary:signer-0.7.0
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/notary/manifests/signer-0.7.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_notary:signer-0.7.0_2024-06-11_18:57:14.json notary:signer-0.7.0] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image notary:signer-0.7.0: failed to pull image notary:signer-0.7.0: GET https://index.docker.io/v2/library/notary/manifests/signer-0.7.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_notary:signer-0.7.0_2024-06-11_18:57:14.json notary:signer-0.7.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
notary:signer ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_notary:signer_2024-06-11_18:57:28.json notary:signer] execution failed: exit status 1
Output: 2024-06-11T18:57:29Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:57:29Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "notary:signer" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (notary:signer): Error response from daemon: No such image: notary:signer
	* containerd error: image not found in containerd store: notary:signer
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/notary/manifests/signer: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_notary:signer_2024-06-11_18:57:28.json notary:signer] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image notary:signer: failed to pull image notary:signer: GET https://index.docker.io/v2/library/notary/manifests/signer: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_notary:signer_2024-06-11_18:57:28.json notary:signer] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
notary:server-0.7.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_notary:server-0.7.0_2024-06-11_18:57:42.json notary:server-0.7.0] execution failed: exit status 1
Output: 2024-06-11T18:57:42Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:57:43Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "notary:server-0.7.0" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (notary:server-0.7.0): Error response from daemon: No such image: notary:server-0.7.0
	* containerd error: image not found in containerd store: notary:server-0.7.0
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/notary/manifests/server-0.7.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_notary:server-0.7.0_2024-06-11_18:57:42.json notary:server-0.7.0] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image notary:server-0.7.0: failed to pull image notary:server-0.7.0: GET https://index.docker.io/v2/library/notary/manifests/server-0.7.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_notary:server-0.7.0_2024-06-11_18:57:42.json notary:server-0.7.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
notary:server ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_notary:server_2024-06-11_18:57:54.json notary:server] execution failed: exit status 1
Output: 2024-06-11T18:57:55Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:57:56Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "notary:server" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (notary:server): Error response from daemon: No such image: notary:server
	* containerd error: image not found in containerd store: notary:server
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/notary/manifests/server: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_notary:server_2024-06-11_18:57:54.json notary:server] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image notary:server: failed to pull image notary:server: GET https://index.docker.io/v2/library/notary/manifests/server: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_notary:server_2024-06-11_18:57:54.json notary:server] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
notary:signer-0.6.1-2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_notary:signer-0.6.1-2_2024-06-11_18:58:10.json notary:signer-0.6.1-2] execution failed: exit status 1
Output: 2024-06-11T18:58:11Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:58:12Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "notary:signer-0.6.1-2" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (notary:signer-0.6.1-2): Error response from daemon: No such image: notary:signer-0.6.1-2
	* containerd error: image not found in containerd store: notary:signer-0.6.1-2
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/notary/manifests/signer-0.6.1-2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_notary:signer-0.6.1-2_2024-06-11_18:58:10.json notary:signer-0.6.1-2] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image notary:signer-0.6.1-2: failed to pull image notary:signer-0.6.1-2: GET https://index.docker.io/v2/library/notary/manifests/signer-0.6.1-2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_notary:signer-0.6.1-2_2024-06-11_18:58:10.json notary:signer-0.6.1-2] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
elixir:1.12.3-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_elixir:1.12.3-slim_2024-06-11_18:58:30.json elixir:1.12.3-slim] execution failed: exit status 1
Output: 2024-06-11T18:58:31Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:58:32Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "elixir:1.12.3-slim" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (elixir:1.12.3-slim): Error response from daemon: No such image: elixir:1.12.3-slim
	* containerd error: image not found in containerd store: elixir:1.12.3-slim
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-slim: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_elixir:1.12.3-slim_2024-06-11_18:58:30.json elixir:1.12.3-slim] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image elixir:1.12.3-slim: failed to pull image elixir:1.12.3-slim: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-slim: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_elixir:1.12.3-slim_2024-06-11_18:58:30.json elixir:1.12.3-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
elixir:1.12.3-otp-24-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_elixir:1.12.3-otp-24-slim_2024-06-11_18:58:50.json elixir:1.12.3-otp-24-slim] execution failed: exit status 1
Output: 2024-06-11T18:58:51Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:58:52Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "elixir:1.12.3-otp-24-slim" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (elixir:1.12.3-otp-24-slim): Error response from daemon: No such image: elixir:1.12.3-otp-24-slim
	* containerd error: image not found in containerd store: elixir:1.12.3-otp-24-slim
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-otp-24-slim: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_elixir:1.12.3-otp-24-slim_2024-06-11_18:58:50.json elixir:1.12.3-otp-24-slim] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image elixir:1.12.3-otp-24-slim: failed to pull image elixir:1.12.3-otp-24-slim: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-otp-24-slim: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_elixir:1.12.3-otp-24-slim_2024-06-11_18:58:50.json elixir:1.12.3-otp-24-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
elixir:1.12.3-otp-24-alpine ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_elixir:1.12.3-otp-24-alpine_2024-06-11_18:59:21.json elixir:1.12.3-otp-24-alpine] execution failed: exit status 1
Output: 2024-06-11T18:59:21Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:59:22Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "elixir:1.12.3-otp-24-alpine" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (elixir:1.12.3-otp-24-alpine): Error response from daemon: No such image: elixir:1.12.3-otp-24-alpine
	* containerd error: image not found in containerd store: elixir:1.12.3-otp-24-alpine
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-otp-24-alpine: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_elixir:1.12.3-otp-24-alpine_2024-06-11_18:59:21.json elixir:1.12.3-otp-24-alpine] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image elixir:1.12.3-otp-24-alpine: failed to pull image elixir:1.12.3-otp-24-alpine: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-otp-24-alpine: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_elixir:1.12.3-otp-24-alpine_2024-06-11_18:59:21.json elixir:1.12.3-otp-24-alpine] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
elixir:1.12.3-alpine ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_elixir:1.12.3-alpine_2024-06-11_18:59:35.json elixir:1.12.3-alpine] execution failed: exit status 1
Output: 2024-06-11T18:59:35Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:59:36Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "elixir:1.12.3-alpine" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (elixir:1.12.3-alpine): Error response from daemon: No such image: elixir:1.12.3-alpine
	* containerd error: image not found in containerd store: elixir:1.12.3-alpine
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-alpine: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_elixir:1.12.3-alpine_2024-06-11_18:59:35.json elixir:1.12.3-alpine] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image elixir:1.12.3-alpine: failed to pull image elixir:1.12.3-alpine: GET https://index.docker.io/v2/library/elixir/manifests/1.12.3-alpine: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_elixir:1.12.3-alpine_2024-06-11_18:59:35.json elixir:1.12.3-alpine] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
elixir:1.12-slim ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_elixir:1.12-slim_2024-06-11_18:59:49.json elixir:1.12-slim] execution failed: exit status 1
Output: 2024-06-11T18:59:50Z	INFO	Vulnerability scanning is enabled
2024-06-11T18:59:51Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "elixir:1.12-slim" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (elixir:1.12-slim): Error response from daemon: No such image: elixir:1.12-slim
	* containerd error: image not found in containerd store: elixir:1.12-slim
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/elixir/manifests/1.12-slim: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_elixir:1.12-slim_2024-06-11_18:59:49.json elixir:1.12-slim] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image elixir:1.12-slim: failed to pull image elixir:1.12-slim: GET https://index.docker.io/v2/library/elixir/manifests/1.12-slim: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_elixir:1.12-slim_2024-06-11_18:59:49.json elixir:1.12-slim] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
lightstreamer:7.4.2-jdk8-temurin ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_lightstreamer:7.4.2-jdk8-temurin_2024-06-11_19:00:12.json lightstreamer:7.4.2-jdk8-temurin] execution failed: exit status 1
Output: 2024-06-11T19:00:13Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:00:13Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "lightstreamer:7.4.2-jdk8-temurin" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (lightstreamer:7.4.2-jdk8-temurin): Error response from daemon: No such image: lightstreamer:7.4.2-jdk8-temurin
	* containerd error: image not found in containerd store: lightstreamer:7.4.2-jdk8-temurin
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk8-temurin: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_lightstreamer:7.4.2-jdk8-temurin_2024-06-11_19:00:12.json lightstreamer:7.4.2-jdk8-temurin] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image lightstreamer:7.4.2-jdk8-temurin: failed to pull image lightstreamer:7.4.2-jdk8-temurin: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk8-temurin: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_lightstreamer:7.4.2-jdk8-temurin_2024-06-11_19:00:12.json lightstreamer:7.4.2-jdk8-temurin] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
lightstreamer:7.4.2-jdk8 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_lightstreamer:7.4.2-jdk8_2024-06-11_19:01:17.json lightstreamer:7.4.2-jdk8] execution failed: exit status 1
Output: 2024-06-11T19:01:18Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:01:18Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "lightstreamer:7.4.2-jdk8" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (lightstreamer:7.4.2-jdk8): Error response from daemon: No such image: lightstreamer:7.4.2-jdk8
	* containerd error: image not found in containerd store: lightstreamer:7.4.2-jdk8
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk8: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_lightstreamer:7.4.2-jdk8_2024-06-11_19:01:17.json lightstreamer:7.4.2-jdk8] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image lightstreamer:7.4.2-jdk8: failed to pull image lightstreamer:7.4.2-jdk8: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk8: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_lightstreamer:7.4.2-jdk8_2024-06-11_19:01:17.json lightstreamer:7.4.2-jdk8] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
lightstreamer:7.4.2-jdk21-temurin ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_lightstreamer:7.4.2-jdk21-temurin_2024-06-11_19:01:44.json lightstreamer:7.4.2-jdk21-temurin] execution failed: exit status 1
Output: 2024-06-11T19:01:45Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:01:45Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "lightstreamer:7.4.2-jdk21-temurin" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (lightstreamer:7.4.2-jdk21-temurin): Error response from daemon: No such image: lightstreamer:7.4.2-jdk21-temurin
	* containerd error: image not found in containerd store: lightstreamer:7.4.2-jdk21-temurin
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk21-temurin: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_lightstreamer:7.4.2-jdk21-temurin_2024-06-11_19:01:44.json lightstreamer:7.4.2-jdk21-temurin] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image lightstreamer:7.4.2-jdk21-temurin: failed to pull image lightstreamer:7.4.2-jdk21-temurin: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk21-temurin: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_lightstreamer:7.4.2-jdk21-temurin_2024-06-11_19:01:44.json lightstreamer:7.4.2-jdk21-temurin] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

lightstreamer:7.4.2-jdk21 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_lightstreamer:7.4.2-jdk21_2024-06-11_19:02:13.json lightstreamer:7.4.2-jdk21] execution failed: exit status 1
Output: 2024-06-11T19:02:13Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:02:14Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "lightstreamer:7.4.2-jdk21" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (lightstreamer:7.4.2-jdk21): Error response from daemon: No such image: lightstreamer:7.4.2-jdk21
	* containerd error: image not found in containerd store: lightstreamer:7.4.2-jdk21
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk21: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_lightstreamer:7.4.2-jdk21_2024-06-11_19:02:13.json lightstreamer:7.4.2-jdk21] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image lightstreamer:7.4.2-jdk21: failed to pull image lightstreamer:7.4.2-jdk21: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk21: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_lightstreamer:7.4.2-jdk21_2024-06-11_19:02:13.json lightstreamer:7.4.2-jdk21] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
lightstreamer:7.4.2-jdk17-temurin ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_lightstreamer:7.4.2-jdk17-temurin_2024-06-11_19:02:40.json lightstreamer:7.4.2-jdk17-temurin] execution failed: exit status 1
Output: 2024-06-11T19:02:41Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:02:42Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "lightstreamer:7.4.2-jdk17-temurin" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (lightstreamer:7.4.2-jdk17-temurin): Error response from daemon: No such image: lightstreamer:7.4.2-jdk17-temurin
	* containerd error: image not found in containerd store: lightstreamer:7.4.2-jdk17-temurin
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk17-temurin: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_lightstreamer:7.4.2-jdk17-temurin_2024-06-11_19:02:40.json lightstreamer:7.4.2-jdk17-temurin] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image lightstreamer:7.4.2-jdk17-temurin: failed to pull image lightstreamer:7.4.2-jdk17-temurin: GET https://index.docker.io/v2/library/lightstreamer/manifests/7.4.2-jdk17-temurin: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_lightstreamer:7.4.2-jdk17-temurin_2024-06-11_19:02:40.json lightstreamer:7.4.2-jdk17-temurin] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

orientdb:3.2.30-tp3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_orientdb:3.2.30-tp3_2024-06-11_19:03:10.json orientdb:3.2.30-tp3] execution failed: exit status 1
Output: 2024-06-11T19:03:10Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:03:11Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "orientdb:3.2.30-tp3" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (orientdb:3.2.30-tp3): Error response from daemon: No such image: orientdb:3.2.30-tp3
	* containerd error: image not found in containerd store: orientdb:3.2.30-tp3
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/orientdb/manifests/sha256:ce4bd700b4034db2ae2409b03ffac338fa474beab1d5b7433fc5017a7d1e0ff8: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_orientdb:3.2.30-tp3_2024-06-11_19:03:10.json orientdb:3.2.30-tp3] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image orientdb:3.2.30-tp3: failed to pull image orientdb:3.2.30-tp3: GET https://index.docker.io/v2/library/orientdb/manifests/3.2.30-tp3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_orientdb:3.2.30-tp3_2024-06-11_19:03:10.json orientdb:3.2.30-tp3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

orientdb:3.2.30 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_orientdb:3.2.30_2024-06-11_19:03:46.json orientdb:3.2.30] execution failed: exit status 1
Output: 2024-06-11T19:03:47Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:03:47Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "orientdb:3.2.30" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (orientdb:3.2.30): Error response from daemon: No such image: orientdb:3.2.30
	* containerd error: image not found in containerd store: orientdb:3.2.30
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/orientdb/manifests/3.2.30: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_orientdb:3.2.30_2024-06-11_19:03:46.json orientdb:3.2.30] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image orientdb:3.2.30: failed to pull image orientdb:3.2.30: GET https://index.docker.io/v2/library/orientdb/manifests/3.2.30: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_orientdb:3.2.30_2024-06-11_19:03:46.json orientdb:3.2.30] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

orientdb:3.2-tp3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_orientdb:3.2-tp3_2024-06-11_19:04:15.json orientdb:3.2-tp3] execution failed: exit status 1
Output: 2024-06-11T19:04:16Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:04:17Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "orientdb:3.2-tp3" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (orientdb:3.2-tp3): Error response from daemon: No such image: orientdb:3.2-tp3
	* containerd error: image not found in containerd store: orientdb:3.2-tp3
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/orientdb/manifests/3.2-tp3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_orientdb:3.2-tp3_2024-06-11_19:04:15.json orientdb:3.2-tp3] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image orientdb:3.2-tp3: failed to pull image orientdb:3.2-tp3: GET https://index.docker.io/v2/library/orientdb/manifests/3.2-tp3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_orientdb:3.2-tp3_2024-06-11_19:04:15.json orientdb:3.2-tp3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

orientdb:3.2 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_orientdb:3.2_2024-06-11_19:04:46.json orientdb:3.2] execution failed: exit status 1
Output: 2024-06-11T19:04:47Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:04:48Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "orientdb:3.2" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (orientdb:3.2): Error response from daemon: No such image: orientdb:3.2
	* containerd error: image not found in containerd store: orientdb:3.2
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/orientdb/manifests/3.2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_orientdb:3.2_2024-06-11_19:04:46.json orientdb:3.2] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image orientdb:3.2: failed to pull image orientdb:3.2: GET https://index.docker.io/v2/library/orientdb/manifests/3.2: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_orientdb:3.2_2024-06-11_19:04:46.json orientdb:3.2] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
orientdb:3.1.20-tp3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_orientdb:3.1.20-tp3_2024-06-11_19:05:16.json orientdb:3.1.20-tp3] execution failed: exit status 1
Output: 2024-06-11T19:05:17Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:05:17Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "orientdb:3.1.20-tp3" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (orientdb:3.1.20-tp3): Error response from daemon: No such image: orientdb:3.1.20-tp3
	* containerd error: image not found in containerd store: orientdb:3.1.20-tp3
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/orientdb/manifests/3.1.20-tp3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_orientdb:3.1.20-tp3_2024-06-11_19:05:16.json orientdb:3.1.20-tp3] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image orientdb:3.1.20-tp3: failed to pull image orientdb:3.1.20-tp3: GET https://index.docker.io/v2/library/orientdb/manifests/3.1.20-tp3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_orientdb:3.1.20-tp3_2024-06-11_19:05:16.json orientdb:3.1.20-tp3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

mongo-express:1.0.2-20-alpine3.19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_mongo-express:1.0.2-20-alpine3.19_2024-06-11_19:05:46.json mongo-express:1.0.2-20-alpine3.19] execution failed: exit status 1
Output: 2024-06-11T19:05:47Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:05:47Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "mongo-express:1.0.2-20-alpine3.19" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (mongo-express:1.0.2-20-alpine3.19): Error response from daemon: No such image: mongo-express:1.0.2-20-alpine3.19
	* containerd error: image not found in containerd store: mongo-express:1.0.2-20-alpine3.19
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0.2-20-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_mongo-express:1.0.2-20-alpine3.19_2024-06-11_19:05:46.json mongo-express:1.0.2-20-alpine3.19] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image mongo-express:1.0.2-20-alpine3.19: failed to pull image mongo-express:1.0.2-20-alpine3.19: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0.2-20-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_mongo-express:1.0.2-20-alpine3.19_2024-06-11_19:05:46.json mongo-express:1.0.2-20-alpine3.19] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
mongo-express:1.0.2-18-alpine3.19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_mongo-express:1.0.2-18-alpine3.19_2024-06-11_19:06:08.json mongo-express:1.0.2-18-alpine3.19] execution failed: exit status 1
Output: 2024-06-11T19:06:09Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:06:09Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "mongo-express:1.0.2-18-alpine3.19" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (mongo-express:1.0.2-18-alpine3.19): Error response from daemon: No such image: mongo-express:1.0.2-18-alpine3.19
	* containerd error: image not found in containerd store: mongo-express:1.0.2-18-alpine3.19
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0.2-18-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_mongo-express:1.0.2-18-alpine3.19_2024-06-11_19:06:08.json mongo-express:1.0.2-18-alpine3.19] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image mongo-express:1.0.2-18-alpine3.19: failed to pull image mongo-express:1.0.2-18-alpine3.19: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0.2-18-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_mongo-express:1.0.2-18-alpine3.19_2024-06-11_19:06:08.json mongo-express:1.0.2-18-alpine3.19] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
mongo-express:1.0-20-alpine3.19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_mongo-express:1.0-20-alpine3.19_2024-06-11_19:06:26.json mongo-express:1.0-20-alpine3.19] execution failed: exit status 1
Output: 2024-06-11T19:06:26Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:06:27Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "mongo-express:1.0-20-alpine3.19" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (mongo-express:1.0-20-alpine3.19): Error response from daemon: No such image: mongo-express:1.0-20-alpine3.19
	* containerd error: image not found in containerd store: mongo-express:1.0-20-alpine3.19
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0-20-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_mongo-express:1.0-20-alpine3.19_2024-06-11_19:06:26.json mongo-express:1.0-20-alpine3.19] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image mongo-express:1.0-20-alpine3.19: failed to pull image mongo-express:1.0-20-alpine3.19: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0-20-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_mongo-express:1.0-20-alpine3.19_2024-06-11_19:06:26.json mongo-express:1.0-20-alpine3.19] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
mongo-express:1.0-18-alpine3.19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_mongo-express:1.0-18-alpine3.19_2024-06-11_19:06:47.json mongo-express:1.0-18-alpine3.19] execution failed: exit status 1
Output: 2024-06-11T19:06:48Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:06:49Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "mongo-express:1.0-18-alpine3.19" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (mongo-express:1.0-18-alpine3.19): Error response from daemon: No such image: mongo-express:1.0-18-alpine3.19
	* containerd error: image not found in containerd store: mongo-express:1.0-18-alpine3.19
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0-18-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_mongo-express:1.0-18-alpine3.19_2024-06-11_19:06:47.json mongo-express:1.0-18-alpine3.19] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image mongo-express:1.0-18-alpine3.19: failed to pull image mongo-express:1.0-18-alpine3.19: GET https://index.docker.io/v2/library/mongo-express/manifests/1.0-18-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_mongo-express:1.0-18-alpine3.19_2024-06-11_19:06:47.json mongo-express:1.0-18-alpine3.19] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
mongo-express:1-20-alpine3.19 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_mongo-express:1-20-alpine3.19_2024-06-11_19:07:07.json mongo-express:1-20-alpine3.19] execution failed: exit status 1
Output: 2024-06-11T19:07:08Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:07:08Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "mongo-express:1-20-alpine3.19" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (mongo-express:1-20-alpine3.19): Error response from daemon: No such image: mongo-express:1-20-alpine3.19
	* containerd error: image not found in containerd store: mongo-express:1-20-alpine3.19
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/mongo-express/manifests/1-20-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_mongo-express:1-20-alpine3.19_2024-06-11_19:07:07.json mongo-express:1-20-alpine3.19] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image mongo-express:1-20-alpine3.19: failed to pull image mongo-express:1-20-alpine3.19: GET https://index.docker.io/v2/library/mongo-express/manifests/1-20-alpine3.19: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_mongo-express:1-20-alpine3.19_2024-06-11_19:07:07.json mongo-express:1-20-alpine3.19] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil>
traefik:v3.0.1 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_traefik:v3.0.1_2024-06-11_19:07:25.json traefik:v3.0.1] execution failed: exit status 1
Output: 2024-06-11T19:07:26Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:07:27Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "traefik:v3.0.1" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (traefik:v3.0.1): Error response from daemon: No such image: traefik:v3.0.1
	* containerd error: image not found in containerd store: traefik:v3.0.1
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/traefik/manifests/v3.0.1: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_traefik:v3.0.1_2024-06-11_19:07:25.json traefik:v3.0.1] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image traefik:v3.0.1: failed to pull image traefik:v3.0.1: GET https://index.docker.io/v2/library/traefik/manifests/v3.0.1: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_traefik:v3.0.1_2024-06-11_19:07:25.json traefik:v3.0.1] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

traefik:v3.0 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_traefik:v3.0_2024-06-11_19:07:54.json traefik:v3.0] execution failed: exit status 1
Output: 2024-06-11T19:07:55Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:07:56Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "traefik:v3.0" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (traefik:v3.0): Error response from daemon: No such image: traefik:v3.0
	* containerd error: image not found in containerd store: traefik:v3.0
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/traefik/manifests/v3.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_traefik:v3.0_2024-06-11_19:07:54.json traefik:v3.0] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image traefik:v3.0: failed to pull image traefik:v3.0: GET https://index.docker.io/v2/library/traefik/manifests/v3.0: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_traefik:v3.0_2024-06-11_19:07:54.json traefik:v3.0] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

traefik:v2.11.3 ----------- <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Trivy] --->> Command [/usr/bin/trivy image -f sarif --scanners vuln -o /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Trivy_scan_traefik:v2.11.3_2024-06-11_19:08:24.json traefik:v2.11.3] execution failed: exit status 1
Output: 2024-06-11T19:08:25Z	INFO	Vulnerability scanning is enabled
2024-06-11T19:08:25Z	FATAL	Fatal error	image scan error: scan error: unable to initialize a scanner: unable to initialize an image scanner: unable to find the specified image "traefik:v2.11.3" in ["docker" "containerd" "podman" "remote"]: 4 errors occurred:
	* docker error: unable to inspect the image (traefik:v2.11.3): Error response from daemon: No such image: traefik:v2.11.3
	* containerd error: image not found in containerd store: traefik:v2.11.3
	* podman error: unable to initialize Podman client: no podman socket found: stat /run/user/0/podman/podman.sock: no such file or directory
	* remote error: GET https://index.docker.io/v2/library/traefik/manifests/v2.11.3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit


 
 NEW ERROR: [---ERROR WITH SCANNER---DockerScout] --->> Command [/usr/bin/docker scout cves --format sarif --epss --details --locations --output /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/DockerScout_scan_traefik:v2.11.3_2024-06-11_19:08:24.json traefik:v2.11.3] execution failed: exit status 1
Output:     ...Pulling
    ✗ Pull failed
[31mERROR  [0m Status: failed to get image traefik:v2.11.3: failed to pull image traefik:v2.11.3: GET https://index.docker.io/v2/library/traefik/manifests/v2.11.3: TOOMANYREQUESTS: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit, Code: 1 
 
 NEW ERROR: [---ERROR WITH SCANNER---Snyk] --->> <nil> 
 NEW ERROR: [---ERROR WITH SCANNER---Grype] --->> Command [/usr/local/bin/grype -o sarif --file /mnt/mydata/docker-vulnerability-analyzer/out/official/new6/Grype_scan_traefik:v2.11.3_2024-06-11_19:08:24.json traefik:v2.11.3] execution failed: exit status 1
Output: [31mfailed to load vulnerability db: unable to get namespaces from store: database disk image is malformed (11)[0m

traefik:v2.11 ----------- Error pulling image traefik:v2.11: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
traefik:mimolette ----------- Error pulling image traefik:mimolette: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
backdrop:fpm ----------- Error pulling image backdrop:fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
backdrop:apache ----------- Error pulling image backdrop:apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
backdrop:1.26.1-fpm ----------- Error pulling image backdrop:1.26.1-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
backdrop:1.26.1-apache ----------- Error pulling image backdrop:1.26.1-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
backdrop:1.26.1 ----------- Error pulling image backdrop:1.26.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
consul:1.15.4 ----------- Error pulling image consul:1.15.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
consul:1.15 ----------- Error pulling image consul:1.15: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
consul:1.14.8 ----------- Error pulling image consul:1.14.8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
consul:1.14 ----------- Error pulling image consul:1.14: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
consul:1.13.9 ----------- Error pulling image consul:1.13.9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
chronograf:1.9.4 ----------- Error pulling image chronograf:1.9.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
chronograf:1.9 ----------- Error pulling image chronograf:1.9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
chronograf:1.10.5 ----------- Error pulling image chronograf:1.10.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
chronograf:1.10 ----------- Error pulling image chronograf:1.10: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
chronograf:1.8.10 ----------- Error pulling image chronograf:1.8.10: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
influxdb:alpine ----------- Error pulling image influxdb:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
influxdb:2.7.6-alpine ----------- Error pulling image influxdb:2.7.6-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
influxdb:2.7.6 ----------- Error pulling image influxdb:2.7.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
influxdb:2.7-alpine ----------- Error pulling image influxdb:2.7-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
influxdb:2.7 ----------- Error pulling image influxdb:2.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kapacitor:1.7.4 ----------- Error pulling image kapacitor:1.7.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kapacitor:1.7 ----------- Error pulling image kapacitor:1.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kapacitor:1.6.6 ----------- Error pulling image kapacitor:1.6.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kapacitor:1.6 ----------- Error pulling image kapacitor:1.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kapacitor:alpine ----------- Error pulling image kapacitor:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
telegraf:alpine ----------- Error pulling image telegraf:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
telegraf:1.30.3-alpine ----------- Error pulling image telegraf:1.30.3-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
telegraf:1.30-alpine ----------- Error pulling image telegraf:1.30-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
telegraf:1.30.3 ----------- Error pulling image telegraf:1.30.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
telegraf:1.30 ----------- Error pulling image telegraf:1.30: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hello-seattle:nanoserver ----------- Error pulling image hello-seattle:nanoserver: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hello-seattle:linux ----------- Error pulling image hello-seattle:linux: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hello-seattle:nanoserver-1809 ----------- Error pulling image hello-seattle:nanoserver-1809: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hello-seattle:nanoserver-1803 ----------- Error pulling image hello-seattle:nanoserver-1803: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hello-seattle:nanoserver-1709 ----------- Error pulling image hello-seattle:nanoserver-1709: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spiped:alpine ----------- Error pulling image spiped:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spiped:1.6.2-alpine ----------- Error pulling image spiped:1.6.2-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spiped:1.6-alpine ----------- Error pulling image spiped:1.6-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spiped:1-alpine ----------- Error pulling image spiped:1-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spiped:1.6.2 ----------- Error pulling image spiped:1.6.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
vault:1.13.3 ----------- Error pulling image vault:1.13.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
vault:1.12.7 ----------- Error pulling image vault:1.12.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
vault:1.11.11 ----------- Error pulling image vault:1.11.11: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
vault:1.13.2 ----------- Error pulling image vault:1.13.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
vault:1.12.6 ----------- Error pulling image vault:1.12.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
clearlinux:base ----------- Error pulling image clearlinux:base: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eggdrop:develop ----------- Error pulling image eggdrop:develop: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eggdrop:stable ----------- Error pulling image eggdrop:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eggdrop:1.9.5 ----------- Error pulling image eggdrop:1.9.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eggdrop:1.9 ----------- Error pulling image eggdrop:1.9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eggdrop:1.9.4 ----------- Error pulling image eggdrop:1.9.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibmjava:sfj ----------- Error pulling image ibmjava:sfj: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibmjava:sdk ----------- Error pulling image ibmjava:sdk: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibmjava:jre ----------- Error pulling image ibmjava:jre: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibmjava:8-sfj ----------- Error pulling image ibmjava:8-sfj: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibmjava:8-sdk ----------- Error pulling image ibmjava:8-sdk: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
openjdk:23-oraclelinux8 ----------- Error pulling image openjdk:23-oraclelinux8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
openjdk:23-jdk-oraclelinux8 ----------- Error pulling image openjdk:23-jdk-oraclelinux8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
openjdk:23-ea-oraclelinux8 ----------- Error pulling image openjdk:23-ea-oraclelinux8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
openjdk:23-ea-jdk-oraclelinux8 ----------- Error pulling image openjdk:23-ea-jdk-oraclelinux8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
openjdk:23-ea-25-oraclelinux8 ----------- Error pulling image openjdk:23-ea-25-oraclelinux8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kong:ubuntu ----------- Error pulling image kong:ubuntu: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kong:3.7.0-ubuntu ----------- Error pulling image kong:3.7.0-ubuntu: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kong:3.7.0 ----------- Error pulling image kong:3.7.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kong:3.7-ubuntu ----------- Error pulling image kong:3.7-ubuntu: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
kong:3.7 ----------- Error pulling image kong:3.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
zookeeper:3.9.2-jre-17 ----------- Error pulling image zookeeper:3.9.2-jre-17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
zookeeper:3.9.2 ----------- Error pulling image zookeeper:3.9.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
zookeeper:3.9-jre-17 ----------- Error pulling image zookeeper:3.9-jre-17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
zookeeper:3.9 ----------- Error pulling image zookeeper:3.9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
zookeeper:3.8.4-jre-17 ----------- Error pulling image zookeeper:3.8.4-jre-17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
storm:2.6.2-jre17 ----------- Error pulling image storm:2.6.2-jre17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
storm:2.6.2 ----------- Error pulling image storm:2.6.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
storm:2.6-jre17 ----------- Error pulling image storm:2.6-jre17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
storm:2.6 ----------- Error pulling image storm:2.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
storm:2.6.1 ----------- Error pulling image storm:2.6.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
plone:python38 ----------- Error pulling image plone:python38: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
plone:5.2.13-python38 ----------- Error pulling image plone:5.2.13-python38: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
plone:5.2.13 ----------- Error pulling image plone:5.2.13: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
plone:5.2-python38 ----------- Error pulling image plone:5.2-python38: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
plone:5.2 ----------- Error pulling image plone:5.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
bash:devel-alpine3.20 ----------- Error pulling image bash:devel-alpine3.20: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
bash:devel-20240603-alpine3.20 ----------- Error pulling image bash:devel-20240603-alpine3.20: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
bash:devel-20240603 ----------- Error pulling image bash:devel-20240603: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
bash:devel ----------- Error pulling image bash:devel: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
bash:4.0.44-alpine3.20 ----------- Error pulling image bash:4.0.44-alpine3.20: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazonlinux:2023.4.20240528.0 ----------- Error pulling image amazonlinux:2023.4.20240528.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazonlinux:2023 ----------- Error pulling image amazonlinux:2023: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazonlinux:2.0.20240529.0 ----------- Error pulling image amazonlinux:2.0.20240529.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazonlinux:2 ----------- Error pulling image amazonlinux:2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazonlinux:2023.4.20240416.0 ----------- Error pulling image amazonlinux:2023.4.20240416.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
composer:2.4.4 ----------- Error pulling image composer:2.4.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
composer:2.4 ----------- Error pulling image composer:2.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
composer:2.3.10 ----------- Error pulling image composer:2.3.10: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
composer:2.3 ----------- Error pulling image composer:2.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
composer:2.2.23 ----------- Error pulling image composer:2.2.23: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-mosquitto:openssl ----------- Error pulling image eclipse-mosquitto:openssl: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-mosquitto:2.0.18-openssl ----------- Error pulling image eclipse-mosquitto:2.0.18-openssl: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-mosquitto:2.0-openssl ----------- Error pulling image eclipse-mosquitto:2.0-openssl: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-mosquitto:2-openssl ----------- Error pulling image eclipse-mosquitto:2-openssl: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-mosquitto:1.6.15-openssl ----------- Error pulling image eclipse-mosquitto:1.6.15-openssl: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
nextcloud:stable-fpm ----------- Error pulling image nextcloud:stable-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
nextcloud:stable-apache ----------- Error pulling image nextcloud:stable-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
nextcloud:stable ----------- Error pulling image nextcloud:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
nextcloud:production-fpm ----------- Error pulling image nextcloud:production-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
nextcloud:production-apache ----------- Error pulling image nextcloud:production-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
silverpeas:6.3.5 ----------- Error pulling image silverpeas:6.3.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
silverpeas:6.3.4 ----------- Error pulling image silverpeas:6.3.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
silverpeas:6.0.2 ----------- Error pulling image silverpeas:6.0.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
silverpeas:6.2 ----------- Error pulling image silverpeas:6.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
silverpeas:6.1.2 ----------- Error pulling image silverpeas:6.1.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swift:slim ----------- Error pulling image swift:slim: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swift:rhel-ubi9-slim ----------- Error pulling image swift:rhel-ubi9-slim: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swift:rhel-ubi9 ----------- Error pulling image swift:rhel-ubi9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swift:noble ----------- Error pulling image swift:noble: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swift:mantic ----------- Error pulling image swift:mantic: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
haxe:4.3.4-windowsservercore-ltsc2022 ----------- Error pulling image haxe:4.3.4-windowsservercore-ltsc2022: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
haxe:4.3.4-windowsservercore-1809 ----------- Error pulling image haxe:4.3.4-windowsservercore-1809: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
haxe:4.3.4-windowsservercore ----------- Error pulling image haxe:4.3.4-windowsservercore: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
haxe:4.3.4 ----------- Error pulling image haxe:4.3.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
haxe:4.3-windowsservercore-ltsc2022 ----------- Error pulling image haxe:4.3-windowsservercore-ltsc2022: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
adminer:standalone ----------- Error pulling image adminer:standalone: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
adminer:fastcgi ----------- Error pulling image adminer:fastcgi: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
adminer:4.8.1-standalone ----------- Error pulling image adminer:4.8.1-standalone: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
adminer:4.8.1-fastcgi ----------- Error pulling image adminer:4.8.1-fastcgi: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
adminer:4.8.1 ----------- Error pulling image adminer:4.8.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
geonetwork:4.4.4 ----------- Error pulling image geonetwork:4.4.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
geonetwork:4.4 ----------- Error pulling image geonetwork:4.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
geonetwork:4.2.9 ----------- Error pulling image geonetwork:4.2.9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
geonetwork:4.2 ----------- Error pulling image geonetwork:4.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
geonetwork:4 ----------- Error pulling image geonetwork:4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
xwiki:stable-postgres-tomcat ----------- Error pulling image xwiki:stable-postgres-tomcat: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
xwiki:stable-postgres ----------- Error pulling image xwiki:stable-postgres: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
xwiki:stable-mysql-tomcat ----------- Error pulling image xwiki:stable-mysql-tomcat: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
xwiki:stable-mysql ----------- Error pulling image xwiki:stable-mysql: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
xwiki:stable-mariadb-tomcat ----------- Error pulling image xwiki:stable-mariadb-tomcat: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
groovy:jdk8-jammy ----------- Error pulling image groovy:jdk8-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
groovy:jdk8 ----------- Error pulling image groovy:jdk8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
groovy:jdk21-jammy ----------- Error pulling image groovy:jdk21-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
groovy:jdk21 ----------- Error pulling image groovy:jdk21: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
groovy:jdk17-jammy ----------- Error pulling image groovy:jdk17-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
znc:slim ----------- Error pulling image znc:slim: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
znc:1.9.0-slim ----------- Error pulling image znc:1.9.0-slim: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
znc:1.9.0 ----------- Error pulling image znc:1.9.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
znc:1.9-slim ----------- Error pulling image znc:1.9-slim: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
znc:1.9 ----------- Error pulling image znc:1.9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
gradle:jdk-lts-and-current-jammy ----------- Error pulling image gradle:jdk-lts-and-current-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
gradle:jdk-lts-and-current-alpine ----------- Error pulling image gradle:jdk-lts-and-current-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
gradle:jdk-lts-and-current ----------- Error pulling image gradle:jdk-lts-and-current: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
gradle:jdk-21-and-22-jammy ----------- Error pulling image gradle:jdk-21-and-22-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
gradle:jdk-21-and-22-alpine ----------- Error pulling image gradle:jdk-21-and-22-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
convertigo:8.2.7 ----------- Error pulling image convertigo:8.2.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
convertigo:8.2 ----------- Error pulling image convertigo:8.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
convertigo:8.2.5 ----------- Error pulling image convertigo:8.2.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
convertigo:8.2.4 ----------- Error pulling image convertigo:8.2.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
convertigo:8.1.0 ----------- Error pulling image convertigo:8.1.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
flink:1.18.1-scala_2.12-java17 ----------- Error pulling image flink:1.18.1-scala_2.12-java17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
flink:1.18.1-scala_2.12-java11 ----------- Error pulling image flink:1.18.1-scala_2.12-java11: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
flink:1.18.1-scala_2.12 ----------- Error pulling image flink:1.18.1-scala_2.12: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
flink:1.18.1-java17 ----------- Error pulling image flink:1.18.1-java17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
flink:1.18.1-java11 ----------- Error pulling image flink:1.18.1-java11: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swipl:stable ----------- Error pulling image swipl:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swipl:9.2.5 ----------- Error pulling image swipl:9.2.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swipl:9.3.6 ----------- Error pulling image swipl:9.3.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swipl:9.2.4 ----------- Error pulling image swipl:9.2.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
swipl:9.3.2 ----------- Error pulling image swipl:9.3.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rust:alpine3.20 ----------- Error pulling image rust:alpine3.20: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rust:alpine ----------- Error pulling image rust:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rust:1.78.0-alpine3.20 ----------- Error pulling image rust:1.78.0-alpine3.20: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rust:1.78.0-alpine ----------- Error pulling image rust:1.78.0-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rust:1.78-alpine3.20 ----------- Error pulling image rust:1.78-alpine3.20: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
mediawiki:stable-fpm-alpine ----------- Error pulling image mediawiki:stable-fpm-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
mediawiki:stable-fpm ----------- Error pulling image mediawiki:stable-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
mediawiki:stable ----------- Error pulling image mediawiki:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
mediawiki:lts-fpm-alpine ----------- Error pulling image mediawiki:lts-fpm-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
mediawiki:lts-fpm ----------- Error pulling image mediawiki:lts-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sl:7 ----------- Error pulling image sl:7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sl:6 ----------- Error pulling image sl:6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
open-liberty:kernel-slim-java8-openj9 ----------- Error pulling image open-liberty:kernel-slim-java8-openj9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
open-liberty:kernel-slim-java17-openj9 ----------- Error pulling image open-liberty:kernel-slim-java17-openj9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
open-liberty:kernel-slim-java11-openj9 ----------- Error pulling image open-liberty:kernel-slim-java11-openj9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
open-liberty:kernel-slim ----------- Error pulling image open-liberty:kernel-slim: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
open-liberty:full-java8-openj9 ----------- Error pulling image open-liberty:full-java8-openj9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
clefos:7.7.1908 ----------- Error pulling image clefos:7.7.1908: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
clefos:7 ----------- Error pulling image clefos:7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
teamspeak:3.13.7 ----------- Error pulling image teamspeak:3.13.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
teamspeak:3.13 ----------- Error pulling image teamspeak:3.13: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
teamspeak:3.13.6 ----------- Error pulling image teamspeak:3.13.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
teamspeak:3.13.5 ----------- Error pulling image teamspeak:3.13.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
teamspeak:3.13.3 ----------- Error pulling image teamspeak:3.13.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
matomo:fpm ----------- Error pulling image matomo:fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
matomo:apache ----------- Error pulling image matomo:apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
matomo:5.0.3-fpm ----------- Error pulling image matomo:5.0.3-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
matomo:5.0.3-apache ----------- Error pulling image matomo:5.0.3-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
matomo:5.0.3 ----------- Error pulling image matomo:5.0.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
yourls:fpm ----------- Error pulling image yourls:fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
yourls:apache ----------- Error pulling image yourls:apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
yourls:1.9.2-fpm ----------- Error pulling image yourls:1.9.2-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
yourls:1.9.2-apache ----------- Error pulling image yourls:1.9.2-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
yourls:1.9.2 ----------- Error pulling image yourls:1.9.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
alt:sisyphus ----------- Error pulling image alt:sisyphus: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
alt:p10 ----------- Error pulling image alt:p10: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
alt:p9 ----------- Error pulling image alt:p9: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
alt:p8 ----------- Error pulling image alt:p8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazoncorretto:8u412-al2023-jre ----------- Error pulling image amazoncorretto:8u412-al2023-jre: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazoncorretto:8u412-al2023 ----------- Error pulling image amazoncorretto:8u412-al2023: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazoncorretto:8u412-al2-native-jre ----------- Error pulling image amazoncorretto:8u412-al2-native-jre: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazoncorretto:8u412-al2-native-jdk ----------- Error pulling image amazoncorretto:8u412-al2-native-jdk: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
amazoncorretto:8u412-al2-generic ----------- Error pulling image amazoncorretto:8u412-al2-generic: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
postfixadmin:fpm ----------- Error pulling image postfixadmin:fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
postfixadmin:apache ----------- Error pulling image postfixadmin:apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
postfixadmin:3.3.13-fpm ----------- Error pulling image postfixadmin:3.3.13-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
postfixadmin:3.3.13-apache ----------- Error pulling image postfixadmin:3.3.13-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
postfixadmin:3.3.13 ----------- Error pulling image postfixadmin:3.3.13: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
fluentd:v1.16.2-debian-1.1 ----------- Error pulling image fluentd:v1.16.2-debian-1.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
fluentd:v1.16-debian-1 ----------- Error pulling image fluentd:v1.16-debian-1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
fluentd:v1.16.2-1.1 ----------- Error pulling image fluentd:v1.16.2-1.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
fluentd:v1.16-1 ----------- Error pulling image fluentd:v1.16-1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
fluentd:v1.16.0-debian-1.0 ----------- Error pulling image fluentd:v1.16.0-debian-1.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sapmachine:ubuntu-noble ----------- Error pulling image sapmachine:ubuntu-noble: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sapmachine:ubuntu-jammy ----------- Error pulling image sapmachine:ubuntu-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sapmachine:ubuntu-focal ----------- Error pulling image sapmachine:ubuntu-focal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sapmachine:ubuntu-24.04 ----------- Error pulling image sapmachine:ubuntu-24.04: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
sapmachine:ubuntu-22.04 ----------- Error pulling image sapmachine:ubuntu-22.04: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
varnish:stable ----------- Error pulling image varnish:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
varnish:old ----------- Error pulling image varnish:old: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
varnish:fresh ----------- Error pulling image varnish:fresh: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
varnish:7.5.0 ----------- Error pulling image varnish:7.5.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
varnish:7.5 ----------- Error pulling image varnish:7.5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
archlinux:multilib-devel-20240101.0.204074 ----------- Error pulling image archlinux:multilib-devel-20240101.0.204074: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
archlinux:multilib-devel ----------- Error pulling image archlinux:multilib-devel: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
archlinux:base-devel-20240101.0.204074 ----------- Error pulling image archlinux:base-devel-20240101.0.204074: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
archlinux:base-devel ----------- Error pulling image archlinux:base-devel: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
archlinux:base-20240101.0.204074 ----------- Error pulling image archlinux:base-20240101.0.204074: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
friendica:stable-fpm ----------- Error pulling image friendica:stable-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
friendica:stable-apache ----------- Error pulling image friendica:stable-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
friendica:stable ----------- Error pulling image friendica:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
friendica:fpm ----------- Error pulling image friendica:fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
friendica:dev-fpm ----------- Error pulling image friendica:dev-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
caddy:builder-alpine ----------- Error pulling image caddy:builder-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
caddy:builder ----------- Error pulling image caddy:builder: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
caddy:alpine ----------- Error pulling image caddy:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
caddy:2.8.4-builder-alpine ----------- Error pulling image caddy:2.8.4-builder-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
caddy:2.8.4-builder ----------- Error pulling image caddy:2.8.4-builder: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
monica:5.0.0-beta.4-fpm ----------- Error pulling image monica:5.0.0-beta.4-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
monica:5.0.0-beta.4-apache ----------- Error pulling image monica:5.0.0-beta.4-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
monica:5.0.0-beta-fpm ----------- Error pulling image monica:5.0.0-beta-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
monica:5.0.0-beta-apache ----------- Error pulling image monica:5.0.0-beta-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
monica:5.0-fpm ----------- Error pulling image monica:5.0-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
phpmyadmin:fpm ----------- Error pulling image phpmyadmin:fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
phpmyadmin:apache ----------- Error pulling image phpmyadmin:apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
phpmyadmin:5.2.1-fpm ----------- Error pulling image phpmyadmin:5.2.1-fpm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
phpmyadmin:5.2.1-apache ----------- Error pulling image phpmyadmin:5.2.1-apache: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
phpmyadmin:5.2.1 ----------- Error pulling image phpmyadmin:5.2.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hitch:1.8.0-1 ----------- Error pulling image hitch:1.8.0-1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hitch:1.8.0 ----------- Error pulling image hitch:1.8.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hitch:1.8 ----------- Error pulling image hitch:1.8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hitch:1 ----------- Error pulling image hitch:1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
hitch:1.7.3-1 ----------- Error pulling image hitch:1.7.3-1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
almalinux:minimal ----------- Error pulling image almalinux:minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
almalinux:9.4-minimal-20240530 ----------- Error pulling image almalinux:9.4-minimal-20240530: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
almalinux:9.4-minimal ----------- Error pulling image almalinux:9.4-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
almalinux:9.4-20240530 ----------- Error pulling image almalinux:9.4-20240530: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
almalinux:9.4 ----------- Error pulling image almalinux:9.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
dart:stable-sdk ----------- Error pulling image dart:stable-sdk: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
dart:stable ----------- Error pulling image dart:stable: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
dart:sdk ----------- Error pulling image dart:sdk: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
dart:beta-sdk ----------- Error pulling image dart:beta-sdk: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
dart:beta ----------- Error pulling image dart:beta: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-temurin:8u412-b08-jre-ubi9-minimal ----------- Error pulling image eclipse-temurin:8u412-b08-jre-ubi9-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-temurin:8u412-b08-jdk-ubi9-minimal ----------- Error pulling image eclipse-temurin:8u412-b08-jdk-ubi9-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-temurin:8-ubi9-minimal ----------- Error pulling image eclipse-temurin:8-ubi9-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-temurin:8-jre-ubi9-minimal ----------- Error pulling image eclipse-temurin:8-jre-ubi9-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
eclipse-temurin:8-jdk-ubi9-minimal ----------- Error pulling image eclipse-temurin:8-jdk-ubi9-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibm-semeru-runtimes:open-8u412-b08-jre-jammy ----------- Error pulling image ibm-semeru-runtimes:open-8u412-b08-jre-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibm-semeru-runtimes:open-8u412-b08-jre-focal ----------- Error pulling image ibm-semeru-runtimes:open-8u412-b08-jre-focal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibm-semeru-runtimes:open-8u412-b08-jre ----------- Error pulling image ibm-semeru-runtimes:open-8u412-b08-jre: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibm-semeru-runtimes:open-8u412-b08-jdk-jammy ----------- Error pulling image ibm-semeru-runtimes:open-8u412-b08-jdk-jammy: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
ibm-semeru-runtimes:open-8u412-b08-jdk-focal ----------- Error pulling image ibm-semeru-runtimes:open-8u412-b08-jdk-focal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rockylinux:9.3.20231119-minimal ----------- Error pulling image rockylinux:9.3.20231119-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rockylinux:9.3.20231119 ----------- Error pulling image rockylinux:9.3.20231119: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rockylinux:9.3-minimal ----------- Error pulling image rockylinux:9.3-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rockylinux:9.3 ----------- Error pulling image rockylinux:9.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
rockylinux:9-minimal ----------- Error pulling image rockylinux:9-minimal: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
api-firewall:0.7.3 ----------- Error pulling image api-firewall:0.7.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
api-firewall:0.7.2 ----------- Error pulling image api-firewall:0.7.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
api-firewall:0.7.1 ----------- Error pulling image api-firewall:0.7.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
api-firewall:0.7.0 ----------- Error pulling image api-firewall:0.7.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
api-firewall:0.6.17 ----------- Error pulling image api-firewall:0.6.17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
emqx:5.7.0 ----------- Error pulling image emqx:5.7.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
emqx:5.7 ----------- Error pulling image emqx:5.7: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
emqx:5 ----------- Error pulling image emqx:5: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
emqx:5.6.1 ----------- Error pulling image emqx:5.6.1: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
emqx:5.6 ----------- Error pulling image emqx:5.6: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
satosa:bookworm ----------- Error pulling image satosa:bookworm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
satosa:8.4.0-bookworm ----------- Error pulling image satosa:8.4.0-bookworm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
satosa:8.4.0 ----------- Error pulling image satosa:8.4.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
satosa:8.4-bookworm ----------- Error pulling image satosa:8.4-bookworm: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
satosa:8.4 ----------- Error pulling image satosa:8.4: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
unit:php8.3 ----------- Error pulling image unit:php8.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
unit:php8.2 ----------- Error pulling image unit:php8.2: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
unit:php8 ----------- Error pulling image unit:php8: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
unit:php ----------- Error pulling image unit:php: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
unit:1.32.1-php8.3 ----------- Error pulling image unit:1.32.1-php8.3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spark:scala ----------- Error pulling image spark:scala: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spark:r ----------- Error pulling image spark:r: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spark:python3-java17 ----------- Error pulling image spark:python3-java17: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spark:python3 ----------- Error pulling image spark:python3: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
spark:3.5.1-scala2.12-java17-ubuntu ----------- Error pulling image spark:3.5.1-scala2.12-java17-ubuntu: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
liquibase:4.28.0 ----------- Error pulling image liquibase:4.28.0: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
liquibase:4.28 ----------- Error pulling image liquibase:4.28: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
liquibase:alpine ----------- Error pulling image liquibase:alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
liquibase:4.28.0-alpine ----------- Error pulling image liquibase:4.28.0-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
liquibase:4.28-alpine ----------- Error pulling image liquibase:4.28-alpine: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
